language: node_js
node_js:
  - "10"
  - "9"
  - "8"

cache: yarn

script:
  - yarn run lint
  - yarn run typecheck
  - yarn run build
  - yarn run test-once --runInBand

after_success:
  - yarn global add codecov && codecov
