language: node_js
node_js:
  - "10"
  - "9"
  - "8"

cache: yarn

script:
  - yarn run lint
  - yarn run typecheck
  - yarn run build
  - yarn run test-once --runInBand

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - yarn global add codecov && codecov
