environment:
  matrix:
  - nodejs_version: "10"
  - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn

test_script:
  - yarn run lint
  - yarn run typecheck
  - yarn run build
  - yarn run test-once --runInBand

build: off
shallow_clone: true
clone_depth: 1
